name: PR tags checks test

on:
  pull_request:
    branches: [ main ]

jobs:

  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Generate file
        run: rm test/test*.txt && echo test2 > test/test1.txt

      - name: Commit files
        run: |
          git config --local user.email "pascal.zimmermann@theiotstudio.com"
          git config --local user.name "ZPascal"
          git add test
          git commit -m "Test the action"
          cat .git/config

      - name: Push changes
        uses: ad-m/github-push-action@f7b8a8025db5c3e448311327d477463725201283
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          repository: ZPascal/test_clone_push_action
          github_user: ZPascal