name: PR tags checks test

on:
  push:
    tags:
      - '*.*.*'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:

  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Generate file
        run: rm docs/test*.txt && echo test8 > docs/test8.txt

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -d $GITHUB_REF_NAME
          git add docs
          git commit -m "Test the action"
          git tag $GITHUB_REF_NAME

      - name: Push changes
        uses: ad-m/github-push-action@a6cda06069df6bbef5e32c407a51470e18b1433a
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true
