name: PR tags checks test

on:
  pull_request:
    branches: [ main ]

jobs:

  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate file
        run: rm test/test*.txt && echo test4 > test/test1.txt

      - name: Commit files
        run: |
          git config --local user.email "pascal.zimmermann@theiotstudio.com"
          git config --local user.name "ZPascal"
          git add test
          git commit -m "Test the action"

      - name: Push changes
        uses: ad-m/github-push-action@37a6671b2ec20a710623be0d38c401c85f066fcf
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          repository: ZPascal/test_clone_push_action
          force_with_lease: true